attendance = set()
attendance.add(1)
attendance.add(2)
attendance.add(3)
print("Initial Attendance:                 ", attendance)
arrived = {4,5,6}
attendance.update(arrived)
print("Updated Attendance:                 ", attendance)
attendance.remove(1)
print("Attendance After Removal:           ", attendance)
attendance.discard(7)
print("Attendance After Discarding:        ", attendance)
oral = attendance.pop()
print("Roll Number For Surprise Oral Test: ", oral)
print("Attendance After Popping:           ", attendance)
attendance.clear()
print(attendance)
